version: "3"
services:
  mongo:
    image: "mongo:3.2"
    hostname: "mongo"
    container_name: "mongo"
    network_mode: "default"
    ports:
        - "27019:27017"
    volumes:
      - "/var/lib/mongodb_docker_client:/data/db"
  app:
    image: "sombrainc/docker-client:1.0-SNAPSHOT"
    hostname: "dockerClient"
    container_name: "dockerClient"
    network_mode: "default"
    ports:
      - "9000:9000"
      - "9999:9999"
    command: ["bin/docker-client", "-Dconfig.file=conf/application.conf", "-Dhttp.port=9000","-DDB_HOST=mongo", "-DDB_PORT=27017", "-jvm-debug", "9999"]
    links:
      - "mongo:mongo"
    depends_on:
      - mongo
    links:
      - "mongo:mongo"
